- .gitignore
- Samples/XLabs.Sample.Droid/XLabs.Sample.Droid.csproj
- src/Forms/Charting/XLabs.Forms.Charting.Droid/XLabs.Forms.Charting.Droid.csproj
- src/Forms/XLabs.Forms.Droid/Controls/RadioButton/RadioButtonRenderer.cs
- src/Forms/XLabs.Forms.iOS/Controls/RadioButton/RadioButtonRenderer.cs
Fix the build in master. It's currently broken due to bad nuget target checks and old namespaces.
> Fix the build

- .gitignore
- Samples/XLabs.Sample.Droid/XLabs.Sample.Droid.csproj
- src/Forms/Charting/XLabs.Forms.Charting.Droid/XLabs.Forms.Charting.Droid.csproj
- src/Forms/XLabs.Forms.Droid/Controls/RadioButton/RadioButtonRenderer.cs
- src/Forms/XLabs.Forms.iOS/Controls/RadioButton/RadioButtonRenderer.cs
- src/Forms/XLabs.Forms/Controls/ContentPresenter.cs
- src/Forms/XLabs.Forms/XLabs.Forms.csproj
This is the implementation for #545
> Implement a WPF-like ContentPresenter control

- src/Forms/XLabs.Forms.Droid/XFormsApp.cs
- src/Forms/XLabs.Forms.iOS/XFormsApp.cs
> Inherit from new Forms specific application related classes

- src/Forms/XLabs.Forms.iOS/Controls/ExtendedEntry/ExtendedEntryRenderer.cs
[BUG] and [FIX] EntendedEntry iOS #575
> ExtendedEntry iOS fix

- src/Forms/XLabs.Forms.iOS/Controls/GridView/GridViewRenderer.cs
- src/Forms/XLabs.Forms/Controls/GridView.cs
- Fixed an issue where the RowsInSection function would crash if the ItemsSource collection was wull.
- Added a SelectedItem property that can be two-way data bound.
> Changes to GridView control behaviour - fixed line endings

- src/Forms/XLabs.Forms/Controls/GesturesContentView.cs
> GestureContentView fix

- Samples/XLabs.Sample/ViewModel/MvvmSampleViewModel.cs
- src/Forms/XLabs.Forms/Mvvm/IViewModel.cs
- src/Forms/XLabs.Forms/Mvvm/ViewFactory.cs
- src/Forms/XLabs.Forms/Mvvm/ViewModel.cs
- src/IOC/XLabs.IoC.Serialization.JsonNET/XLabs.IoC.Serialization.JsonNET.csproj
- src/IOC/XLabs.IoC.Serialization.JsonNET/packages.config
Related with #541 our navigation service is too simple yet, let's keep the old one around and then move it from there.
> [Forms] Add old navigation back and keep the new one

- Samples/XLabs.Sample/ViewModel/SoundServiceViewModel.cs
- src/Forms/XLabs.Forms.Droid/XFormsApp.cs
- src/Forms/XLabs.Forms.WP8/XFormsApp.cs
- src/Forms/XLabs.Forms.iOS/XFormsApp.cs
- src/Platform/XLabs.Platform/Mvvm/IXFormsApp.cs
- src/Platform/XLabs.Platform/Mvvm/XFormsApp.cs
This will help with people porting and that rely on DependencyService, the user can opt out.
> [Forms] Initialize services with DependencyService

- src/Forms/XLabs.Forms/Mvvm/BaseView.cs
- src/Forms/XLabs.Forms/Mvvm/ViewModel.cs
This is my first ever git fork & pull request so please be gentle :) I hope I've done everything right.
This is just a little thing, but it's a couple of virtual methods so you can hook into the page appearing and disappearing from the viewmodel rather than from the view. If you don't think it's useful then feel free not to accept it - it was just something I've found useful in a couple of instances and thought you might agree.
> Added virtual methods to hook into the view appearing/disappearing from within the viewmodel

- Samples/XLabs.Sample.WP/XLabs.Sample.WP.csproj
- Samples/XLabs.Sample.WP/packages.config
- Samples/XLabs.Sample/ViewModel/GeolocatorViewModel.cs
- src/Forms/Charting/XLabs.Forms.Charting.WP/XLabs.Forms.Charting.WP.csproj
- src/Forms/Charting/XLabs.Forms.Charting.WP/packages.config
- src/Forms/XLabs.Forms.WP8/XLabs.Forms.WP8.csproj
- src/Forms/XLabs.Forms.WP8/packages.config
- src/Forms/XLabs.Forms/Mvvm/ViewModelNavigation.cs
- src/Platform/XLabs.Platform.Droid/Services/Geolocation/GeolocationContinuousListener.cs
- src/Platform/XLabs.Platform.Droid/Services/Geolocation/GeolocationSingleListener.cs
- src/Platform/XLabs.Platform.Droid/Services/Geolocation/Geolocator.cs
- src/Platform/XLabs.Platform.WP8/Extensions/DeviceExtensions.cs
- src/Platform/XLabs.Platform.WP8/Services/Geolocation/CoordinateExtensions.cs
- src/Platform/XLabs.Platform.WP8/Services/Geolocation/Geolocator.cs
- src/Platform/XLabs.Platform.iOS/Services/Geolocation/GeolocationSingleUpdateDelegate.cs
- src/Platform/XLabs.Platform.iOS/Services/Geolocation/Geolocator.cs
- src/Platform/XLabs.Platform/Extensions/PositionExtensions.cs
- src/Platform/XLabs.Platform/Services/GeoLocation/IGeolocator.cs
- src/Platform/XLabs.Platform/Services/GeoLocation/Position.cs
- src/Platform/XLabs.Platform/Services/GeoLocation/PositionExtensions.cs
I have added the animated parameter and RemovePage method to bring the new features from XF 1.3.0 into the ViewModelNavigation class.
> Added navigation parameters and methods introduced in XF 1.3.0

- src/Platform/XLabs.Platform.iOS/Device/AppleDevice.cs
Avoids asking for permissions if not necessary
> Initialize Bluetooth hub on demand

- src/Forms/XLabs.Forms.Droid/Controls/ExtendedScrollView/ExtendedScrollViewRenderer.cs
- src/Forms/XLabs.Forms.Droid/Controls/GesturesContentView/GesturesContentViewRenderer.cs
- src/Forms/XLabs.Forms/Behaviors/GestureResult.cs
- src/Forms/XLabs.Forms/Controls/GesturesContentView.cs
The gesture additions are only implemented and tested under Android for now.
> gesture additions and small scrollview fix

- src/Forms/XLabs.Forms.Droid/Resources/layout/calendar_pager_layout.xml
- src/Forms/XLabs.Forms.Droid/Resources/layout/calendar_picker.xml
- src/Forms/XLabs.Forms.Droid/Resources/layout/dialog.xml
- src/Forms/XLabs.Forms.Droid/Resources/layout/month.xml
- src/Forms/XLabs.Forms.Droid/Resources/layout/week.xml
java.lang.ClassNotFoundException: Didn't find class "xamarin.forms.labs.droid.controls.calendar.CalendarPickerView" on path: DexPathList
> Solved -> Calendar Control (Android)

- Samples/XLabs.Sample.Droid/MainActivity.cs
- Samples/XLabs.Sample.WP/App.xaml.cs
- Samples/XLabs.Sample.iOS/AppDelegate.cs
- Samples/XLabs.Sample/App.cs
- Samples/XLabs.Sample/Pages/Services/SecureStoragePage.xaml
- Samples/XLabs.Sample/Pages/Services/SecureStoragePage.xaml.cs
- Samples/XLabs.Sample/XLabs.Sample.csproj
- src/Platform/XLabs.Platform.Droid/Services/KeyVaultStorage.cs
- src/Platform/XLabs.Platform.Droid/Services/SharedPreferencesStorage.cs
- src/Platform/XLabs.Platform.Droid/XLabs.Platform.Droid.csproj
- src/Platform/XLabs.Platform.WP8/Services/SecureStorage.cs
- src/Platform/XLabs.Platform.WP8/XLabs.Platform.WP8.csproj
- src/Platform/XLabs.Platform.iOS/Services/SecureStorage.cs
- src/Platform/XLabs.Platform.iOS/XLabs.Platform.iOS.csproj
- src/Platform/XLabs.Platform/Services/ISecureStorage.cs
- src/Platform/XLabs.Platform/XLabs.Platform.csproj
Implemented for Android using both shared preferences and KeyStore. Single implementations for iOS & WP.
> Added interface for Secure Storage

- CHANGELOG.md
I think it's time to start logging changes to a source controlled change log file. 
I have created a place-holder only. If @sami1971 or @rmarinho can pre-populate something for previous versions. This would help guide future amendments. 
If you accept this PR and merge, then I will update the [Contributors Guide](https://github.com/XLabs/Xamarin-Forms-Labs/wiki/XLabs-Contributors-Guide) to the effect that all Pull Requests (PR) should include this file. You should then the workflow would be to not accept any PR's unless this file reflects the changes made in that PR.
Cheers
Nicholas
> Added a placeholder CHANGELOG.md

- src/Platform/XLabs.Platform.iOS/Services/Geolocation/Geolocator.cs
> [iOS] Remove iOS8 conditional compilation directive

- src/Forms/XLabs.Forms/Mvvm/BaseView.cs
> [Forms] Call the correct view disappearing

- src/Forms/XLabs.Forms.Droid/Controls/ExtendedScrollView/ExtendedScrollViewRenderer.cs
This is solved https://bugzilla.xamarin.com/show_bug.cgi?id=26214 so we can remove the code
> Remove InputTransparent fixed

- src/Forms/XLabs.Forms.Droid/Controls/GridView/GridViewRenderer.cs
fix GridView not shown on Android (first argument for ExportRenderer sho...uld be XLabs.Forms.Controls.GridView, not Android.Widget.GridView)
> fix GridView not being shown on Android

- src/Forms/XLabs.Forms.iOS/Controls/Calendar/CalendarViewRenderer.cs
https://github.com/XLabs/Xamarin-Forms-Labs/issues/739
> Fix for iOS calendar view renderer

- Samples/XLabs.Sample/Pages/Controls/ExtendedLabelPage.xaml.cs
- src/Forms/XLabs.Forms.iOS/Controls/ExtendedLabel/ExtendedLabelRenderer.cs
- src/Forms/XLabs.Forms/Controls/ExtendedLabel.cs
Ability to edit the shadow of a ExtendedLabel #834
> Added ExtendedLabel ShadowColor

- src/Forms/XLabs.Forms.iOS/Controls/BindablePick/BindablePickerRenderer.cs
- src/Forms/XLabs.Forms.iOS/Controls/Calendar/CalendarViewRenderer.cs
- src/Forms/XLabs.Forms.iOS/Controls/CheckBox/CheckBoxRenderer.cs
- src/Forms/XLabs.Forms.iOS/Controls/EditableListView/EditableListViewRenderer.cs
- src/Forms/XLabs.Forms.iOS/Controls/ExtendedTimePick/ExtendedTimePickerRenderer.cs
- src/Forms/XLabs.Forms.iOS/Controls/GridView/GridViewRenderer.cs
- src/Forms/XLabs.Forms.iOS/Controls/Separator/SeparatorRenderer.cs
We should try to proper cleanup our resources as well as implement the reuse pattern on renderers.
Lot's of leaks.. please help by going throw the renderes and re-evaluate
> [iOS] Severer renderer fixes and dispose cleanup

- .nuget/Definition/XLabs.Platform.NuSpec
> Profile259 support for XLabs.Platform NuSpec

- .nuget/Definition/XLabs.Forms.NuSpec
- .nuget/Definition/XLabs.Platform.NuSpec
- .nuget/Definition/XLabs.Settings.NuSpec
- .nuget/Definition/XLabs.Settings.XamSettings.NuSpec
- XLabs.sln
- src/Forms/XLabs.Forms.WP8/XLabs.Forms.WP8.csproj
- src/Serialization/SystemTextJson/XLabs.Serialization.SystemTextJson.WP8.csproj
- src/Settings/XLabs.Settings.XamSettings/Helpers/Settings.cs
- src/Settings/XLabs.Settings.XamSettings/Properties/AssemblyInfo.cs
- src/Settings/XLabs.Settings.XamSettings/XLabs.Settings.XamSettings.csproj
- src/Settings/XLabs.Settings.XamSettings/XamSettingsConfigSettings.cs
- src/Settings/XLabs.Settings.XamSettings/packages.config
- src/Settings/XLabs.Settings/ConfigSettingsMgr.cs
- src/Settings/XLabs.Settings/GenericConfigSettingsMgr.cs
- src/Settings/XLabs.Settings/IConfigSettingsMgr.cs
- src/Settings/XLabs.Settings/Properties/AssemblyInfo.cs
- src/Settings/XLabs.Settings/SimpleConfigSettingsMgr.cs
- src/Settings/XLabs.Settings/XLabs.Settings.csproj
Added new generic settings framework and 2 implementations (Simple and one provider based on XamSettings)
Fixed a few build path issues
> Support for New Settings Framework

- src/IOC/XLabs.Ioc.Ninject/NinjectContainer.cs
Fix register on Ninject (e.g. container.Register<IService, Service>())
> Fix register in NinjectContainer.cs

- src/Forms/XLabs.Forms/Controls/CarouselView.cs
- src/Forms/XLabs.Forms/Controls/DataTemplateSelector.cs
- src/Forms/XLabs.Forms/Controls/ExtendedListView.cs
- src/Forms/XLabs.Forms/Controls/ExtendedTabbedPage.cs
- src/Forms/XLabs.Forms/Controls/RepeaterView.cs
- src/Forms/XLabs.Forms/Controls/TemplateContentView.cs
Rebase pull request [557] (https://github.com/XLabs/Xamarin-Forms-Labs/pull/557).
> Add DataTemplateSupport to ListView and existing types as per #546

- src/Forms/XLabs.Forms.Droid/Controls/ExtendedEntry/ExtendedEntryRenderer.cs
Fixes the default font used in a password field.
Changes the font to the default font instead of some old Serif font.
> Fixed default font in password field.

- src/Platform/XLabs.Platform.Droid/Services/Media/MediaPickerActivity.cs
See:
https://forums.xamarin.com/discussion/43908/issue-with-xlabs-mediapicker-selectpicture-and-selectvideo
https://code.google.com/p/android/issues/detail?can=2&start=0&num=100&q=&colspec=ID%20Type%20Status%20Owner%20Summary%20Stars&groupby=&sort=&id=175157
> Fix uri for mediapicker using new gallery app

- Samples/XLabs.Sample/App.cs
- Samples/XLabs.Sample/Pages/Controls/ExtendedSwitchPage.xaml
- Samples/XLabs.Sample/Pages/Controls/ExtendedSwitchPage.xaml.cs
- Samples/XLabs.Sample/XLabs.Sample.csproj
ExtendedSwitch sample page displaying one switch with default options and one switch with TintColor set.
> Added sample for ExtendedSwitch

- src/Forms/XLabs.Forms.Droid/Controls/ExtendedTextCell/ExtendedTextCellRenderer.cs
- src/Forms/XLabs.Forms/Controls/ButtonGroup.cs
Safety check for if index is less than 0, as it is will also throw
OutOfRangeException.  Check issue #963.
> Fix: possible OutOfRangeException (#963)

- src/Forms/XLabs.Forms.Droid/Controls/ExtendedTextCell/ExtendedTextCellRenderer.cs
Background Color
Font Size
Font Name
Show disclosure
Disclosure image
> Completed some of the android features #523

- README.md
> Typo in IssueTracker URL

- Samples/XLabs.Sample/App.cs
- Samples/XLabs.Sample/Pages/Controls/ExtendedTextCellPage.xaml
- Samples/XLabs.Sample/Pages/Controls/ExtendedTextCellPage.xaml.cs
- Samples/XLabs.Sample/XLabs.Sample.csproj
> ETC Sample

- Samples/XLabs.Sample/App.cs
- Samples/XLabs.Sample/Pages/Controls/ExtendedPickerPage.xaml
- Samples/XLabs.Sample/Pages/Controls/ExtendedPickerPage.xaml.cs
- src/Forms/XLabs.Forms/Controls/ExtendedPicker.cs
Extends the Picker to allow for DataBinding.
Adds the properties
ItemsSource
DisplayProperty
SelectedItem 
to the base Picker class.
> ExtendedPicker along with sample code.

- src/Forms/XLabs.Forms/Mvvm/ViewFactory.cs
I think that the ability to flush the cache can be useful and it is a small, isolated change.
> ADDED : Ability to clear page cache

- Samples/XLabs.Sample/App.cs
- Samples/XLabs.Sample/Pages/Controls/ExtendedTimePickerPage.cs
- Samples/XLabs.Sample/XLabs.Sample.csproj
- src/Forms/XLabs.Forms.iOS/Controls/ExtendedTimePick/ExtendedTimePickerRenderer.cs
- src/Forms/XLabs.Forms/Controls/ExtendedTimePicker.cs
> Minimum And Maximum Date for ExtendedTimePicker

- Samples/XLabs.Sample.iOS/Info.plist
- Samples/XLabs.Sample/App.cs
- Samples/XLabs.Sample/Pages/Controls/HypberLinkLabelPage.xaml
- Samples/XLabs.Sample/Pages/Controls/HypberLinkLabelPage.xaml.cs
- Samples/XLabs.Sample/XLabs.Sample.csproj
- appveyor.yml
- src/Forms/XLabs.Forms.Droid/XLabs.Forms.Droid.csproj
- src/Forms/XLabs.Forms.WP8/XLabs.Forms.WP8.csproj
- src/Forms/XLabs.Forms.iOS/Controls/HyperLinkLabel/HyperLinkLabelRenderer.cs
- src/Forms/XLabs.Forms.iOS/XLabs.Forms.iOS.csproj
- src/Forms/XLabs.Forms/Controls/HyperLinkLabel.cs
- src/Platform/XLabs.Platform.WP81/packages.config
- src/Platform/XLabs.Platform.WinUniversal/packages.config
Changed HyperLinkLabel to leverage gestures and added sample
> Fix for Issue 1060

- .nuget/Definition/XLabs.Web.NuSpec
- .nuget/Definition/XLabs.Web.Portable.NuSpec
- XLabs.sln
- src/Web/XLabs.Web/XLabs.Web.Droid.csproj
- src/Web/XLabs.Web/XLabs.Web.Net45.csproj
- src/Web/XLabs.Web/XLabs.Web.PortableClient.csproj
- src/Web/XLabs.Web/XLabs.Web.csproj
- src/Web/XLabs.Web/packages.XLabs.Web.Droid.config
- src/Web/XLabs.Web/packages.XLabs.Web.Net45.config
- src/Web/XLabs.Web/packages.XLabs.Web.config
- src/Web/XLabs.Web/packages.XLabs.Web.iOS.config
@ravensorb could you check out this fix?
https://github.com/XLabs/Xamarin-Forms-Labs/issues/1115
> Fix for XLabs.Web packages and NuGet

- README.md
Orientation accepts `ImageOrientation` not plain `Orientation`
> update orientation enum usage

- Samples/XLabs.Sample/Pages/Services/ExtendedDeviceInfoPage.cs
Add Network Connetcions and Device Language information
> Add Network Connetcions and Device Language

- Samples/XLabs.Sample/Pages/Services/ExtendedDeviceInfoPage.cs
>  Device Name Information

- src/Platform/XLabs.Platform.Droid/Services/Media/MediaPickerActivity.cs
https://github.com/XLabs/Xamarin-Forms-Labs/issues/1221
Tested on Galaxy S4 and Nexus 6.
> Fixed issue #1221 with loading photos using Google Photos app.

- README.md
The files were removed in c1dd5ee3719b9116e4ba966a6da41b0b94a19b29
> Remove Helper section in README.md

- src/Caching/XLabs.Caching.Sqlite/SQLiteSimpleCache.cs
Basically works the same way MemoryCache does with checking if it is past expiration when getting the object.
> Implemented cache expiration for SQLite caching

- README.md
There is decent confusion in the community on this project and if it is "dead" or not. Recent interviews with Rui show that it is "dead" and it does not appear to be maintained anymore.
This aims to try and clear up that confusion so they don't install it and wonder why it does not work with recent Xamarin.Forms versions.
> Update README.md with notice
