src/Forms/XLabs.Forms.iOS/Controls/GridView/GridCollectionView.cs
src/Forms/XLabs.Forms.iOS/Controls/GridView/GridViewRenderer.cs

This pull request fixes a sporadic NullReferenceException that happens while scrolling a GridView control.

Fix for #522: GridView crashes on iOS: indexPath == null in GetCell

---

src/Forms/XLabs.Forms/Controls/CheckBox.cs

This makes it far easier for people to hook into the CheckedChanged event also ridding potential bugs with bindings

Changed CheckedChanged to be an event

---

src/Platform/XLabs.Platform.iOS/Services/Geolocation/GeolocationSingleUpdateDelegate.cs
src/Platform/XLabs.Platform.iOS/Services/Geolocation/Geolocator.cs

Reenable the timestamp in the position data after migrating to the unified project.

Set timestamp in iOS Geolocation

---

src/IOC/XLabs.Ioc.Ninject/NinjectContainer.cs

Currently any types registering to themselves causes a runtime NullReferenceException within Ninject when you try to resolve them.
I've added a check in NinjectContainer register method to ensure self registering types are correctly registered.

Fixed problem with NinjectContainer regarding self registering types

---

src/Forms/XLabs.Forms.iOS/Controls/CheckBox/CheckBoxRenderer.cs

Fixes #649.
I also provided two projects with this error:
- https://github.com/pauloortins/CheckboxNotAppearingiOS is an example project using the newest version of both Xamarin.Forms (1.4.0) and XLabs (2.0.5546.35667).
- https://github.com/pauloortins/Xamarin-Forms-Labs/tree/checkbox-error, is the error occurring in the XLabs Project, I created a new page in the controls section called CheckBoxWithError, so you can see it happening.

Fix checkbox error when pop a page asynchronously

---

src/Forms/XLabs.Forms.iOS/Controls/CheckBox/CheckBoxView.cs

Only changed the path to the image resource, case sensitive

Fix for: #658 - XLabs.Forms.iOS - Controls - CheckBox: Image not show

---

src/Forms/XLabs.Forms.iOS/Controls/CheckBox/CheckBoxRenderer.cs

When specified in XAML FontSize isn’t applied if FontName hasn’t been
specified.
I'm not sure if this is the correct fix for this or not. It does work when used with the Samples app.

Fix for FontSize not working

---

Samples/XLabs.Sample/Pages/Controls/ExtendedLabelPage.xaml
Samples/XLabs.Sample/Pages/Controls/ExtendedLabelPage.xaml.cs
src/Forms/XLabs.Forms.Droid/Controls/ExtendedLabel/ExtendedLabelRenderer.cs
src/Forms/XLabs.Forms.WP8/Controls/ExtendedLabel/ExtendedLabelRenderer.cs
src/Forms/XLabs.Forms.iOS/Controls/ExtendedLabel/ExtendedLabelRenderer.cs
src/Forms/XLabs.Forms/Controls/ExtendedLabel.cs

Reverts XLabs/Xamarin-Forms-Labs#672
According to latest XF implementation, there is no way to use custom font in Android without a CustomRenderer. Therefore FontName and FontFriendlyName should not be removed and should be added back.

Revert "Fixes to ExtendedLabel, remove font related properties"

---

src/Platform/XLabs.Platform.iOS/Services/Email/EmailService.cs

The window root view controller will not always be the one that iOS
considers the topmost. If a view controller is presented modally on top
of the root view, this modal should be used for presenting the email
sheet.
The code travels upwards through “PresentedViewController” until the
topmost is reached.

Fixed bug where email sheet was not presented if top controller was modal

---

src/Forms/XLabs.Forms/Controls/GesturesContentView.cs

On Anroid swiping over empty area causes exception.

fix Index Out Of Range Exception

---

src/Forms/XLabs.Forms.iOS/Controls/ImageButton/ImageButtonRenderer.cs

The ImageButton Label behaviour is inconsistent between iOS and Android. The Android button wraps while the iOS button truncates. Until this is exposed as a property, I suggest changing the iOS behaviour to match Android.

Changed linebreakmode on ImageButton on iOS to match Android behavior

---

src/Forms/XLabs.Forms/Mvvm/ViewFactory.cs
src/Forms/XLabs.Forms/Services/NavigationService.cs
src/Platform/XLabs.Platform/Services/INavigationService.cs

This problem have led ```NavigationService.NavigateTo()``` unable to take arguments for constructing view class.
------
Now you can do that like so:
```csharp
NavigationService.NavigateTo<YourViewModel>(true, arguments)
```
The definitions as follows :
void NavigateTo<T>(bool animated = true, params object[] args) where T : class;
void NavigateTo(string pageKey, bool animated = true, params object[] args);
void NavigateTo(Type pageType, bool animated = true, params object[] args);
The last parameter args on these methods is a list that can put some parameters for constructing your view class.
------
**NOTICE:**
Function definitions of `NavigateTo()` have been changed, code might contain some compilation errors.
------
See also: https://github.com/XLabs/Xamarin-Forms-Labs/issues/668

Fixed issue #668

---

src/Platform/XLabs.Platform.iOS/Services/Media/SoundService.cs

Use `Compare() != 0` instead of `> 0` because `Compare()` might return -1 depending on the inputs.

Fix Issue #860

---

src/Forms/XLabs.Forms.iOS/Controls/GesturesContentView/GesturesContentViewRenderer.cs

LongPress gesture will be process a DoubleTap gesture before on GesturesContentView. The change in this pull request fixed the problem.

Fixed LongPress gesture

---

src/Forms/XLabs.Forms/Controls/WrapLayout.cs

The size of the WrapLayout was calculated using both visible and
non-visible children. The non-visible children are not shown in any
case and the result is an empty space.

During calculation of size, only take visible children into account

---

src/Forms/XLabs.Forms.Droid/Controls/ImageButton/ImageButtonRenderer.cs
src/Forms/XLabs.Forms.iOS/Controls/ImageButton/ImageButtonRenderer.cs
src/Forms/XLabs.Forms/Controls/ImageButton.cs

Images from sites such as Iconfinder are black & white only. The ImageTintColor property allows you to add a black & white image and change it's color simply by supplying a ImageTintColor. This also works for Disabled states (no need for a DisabledImageSource)
PS: There's an inconsistency in Xamarin.Forms where the disabled iOS button gets greyed out but this does not happen on Android - I have not fixed this.

Added TintColor support to ImageButton

---

src/Forms/XLabs.Forms.Droid/Controls/WebImage/WebImageRenderer.cs

Prevent null pointer exception if ImageUrl is not specified when call
webClient.DownloadData

Prevent null pointer exception

---

src/Forms/XLabs.Forms.Droid/Controls/RadioButton/RadioButtonRenderer.cs

Not removing (rather adding) event handler to old element's PropertyChanged event leads to leaking.
Dispose implementation caused crash when navigating back from a Page that contains a CustomRadioButton.

fix: Android RadioButtonRenderer can leak, Dispose causes crash

---

src/Forms/XLabs.Forms.Droid/Controls/RadioButton/RadioButtonRenderer.cs

OnElementChanged does not (always) being called when the renderer is being detached. So we should have implemented Dispose and unhook ElementOnPropertyChanged there also.
However after some testing it seems overriding OnElementPropertyChanged is working fine also and this results in a cleaner and smaller code. If it still does not work well, I'm going to implement the first way.

fix: ElementOnPropertyChanged can remain hooked after detaching renderer

---

src/Platform/XLabs.Platform.Droid/Extensions/IntentExtensions.cs
src/Platform/XLabs.Platform.Droid/Services/Email/EmailService.cs

Change the Intent ExtraStream from a single Extra to a
ParcelableArrayListExtra, so we can send multiple attachments to the
Android mail clients. Otherwise only one attachment will be added.
The intent itself has been changed to ActionSendMultiple to achieve the
same goal.
fixes #1001
PS: the coding style has a lot of mixed usage of tabs and spaces. Contribution guidelines would be nice.

Add multiple attachments with Android

---

src/Platform/XLabs.Platform.Droid/Services/Media/MediaPickerActivity.cs

Even if permission is set in manifest it ignores it and throws an error:
http://stackoverflow.com/a/32856112/2987066

Fix for issue where even if Permission bug

---

src/Forms/XLabs.Forms/Validation/Action.cs

ImageSourceConverter appears to be a TypeConverter in /src/Forms/XLabs.Forms/Controls/ImageButtonSourceConverter.cs
Added namespace:
{ typeof(ImageSource), new Controls.ImageSourceConverter() },
to address this error:
Error	CS0104	'ImageSourceConverter' is an ambiguous reference between 'XLabs.Forms.Controls.ImageSourceConverter' and 'Xamarin.Forms.ImageSourceConverter'	XLabs.Forms	\Xamarin-Forms-Labs\src\Forms\XLabs.Forms\Validation\Action.cs	54

ImageSourceConverter is an ambiguous reference

---

src/Forms/XLabs.Forms.Droid/Controls/ExtendedTextCell/ExtendedTextCellRenderer.cs

Passed along "item", a Cell cast as an ExtendedTextCell to BaseCellView which is requesting both a context and a cell.
Error	CS7036	There is no argument given that corresponds to the required formal parameter 'cell' of 'BaseCellView.BaseCellView(Context, Cell)'	XLabs.Forms.Droid	\Xamarin-Forms-Labs\src\Forms\XLabs.Forms.Droid\Controls\ExtendedTextCell\ExtendedTextCellRenderer.cs	58

BaseCellView calls for a context and a cell.

---

src/Platform/XLabs.Platform.Droid/Services/Media/MediaPickerActivity.cs

Added Android namespace, otherwise Manifest is not found in the new permission check.
if (global::Android.OS.Build.VERSION.Release == "6.0")
{
if (CheckSelfPermission(Manifest.Permission.Camera) != Android.Content.PM.Permission.Granted)
{
RequestPermissions(new string[] { Manifest.Permission.Camera }, 1);
}
}

Added Android namespace

---

Samples/XLabs.Sample/App.cs
Samples/XLabs.Sample/Pages/Controls/CarouselSample.xaml
Samples/XLabs.Sample/Pages/Controls/CarouselSample.xaml.cs
src/Forms/XLabs.Forms.iOS/Controls/GesturesContentView/GesturesContentViewRenderer.cs
src/Forms/XLabs.Forms/Controls/CarouselView.cs

Updated the CarouselView control so that swiping works on iOS. 
Also added new property so that consumers can determine / set the current selected item.

Carousel fixes for swipe gestures, new property to get/set selected carousel page

---

src/Forms/XLabs.Forms.iOS/Controls/ImageButton/ImageButtonRenderer.cs

When the Text on the ImageButton was big, the Image wouldn't align in the center of the Button, it would drag itself to the left.
Here is a before and after image:
http://imgur.com/a/0KFWD

Updated ImageOnTop rendering in iOS

---

Samples/XLabs.Sample/Pages/Controls/GridViewPage.xaml
Samples/XLabs.Sample/ViewModel/MainViewModel.cs
src/Forms/XLabs.Forms.iOS/Controls/GridView/GridViewRenderer.cs

Current GridViewRenderer does not handle a change of item source elegantly, and instead ignores any change to its binding.  I changed the naming because it looks like there may have been confusion form the original writer (or from me, although inverting the +/- worked for me).  The DataCollectionChanged force-call is required once, otherwise there won't be any updates until the collection changes again (insert/delete)
Additionally ReloadData is a bit heavy if people are working with large collectionViews, I haven't made any changes there but it might be nice if people are modifying larger data sets (not rebinding)

Update GridViewRenderer to appropriately handle change of ItemsSource

---

src/Forms/XLabs.Forms.iOS/Controls/Calendar/CalendarViewRenderer.cs

When using the calendar view on iOS together with a MaterDetailPage, the app crashes when changing pages.

iOS CalendarViewRenderer: fix NullReferenceException

---

tools/settingsUtils.cake
tools/versionUtils.cake

* new keyword not needed it doesn't replace any base method
* mono script doesn't support enums, so changed to class/static properties instead

Make mono script compatible.

---

src/Forms/XLabs.Forms.Droid/Controls/ExtendedEntry/ExtendedEntryRenderer.cs

Manipulating the Entry Background we are able to remove its borders.
It's quite a simple solution, not sure if it will crash backward compatibility.
Tested with: 
Xamarin.Forms 2.3.2.1127
Xamarin.Android.Support.v4 23.4.0.1
Target: Android API 23

Added support for no border ExtenedEntry on Android

---

src/Platform/XLabs.Platform.iOS/Device/Phone.cs

There appears to be an issue detecting zoom mode on the iPhone6 and iPhone6+. 
I've added detection for zoom mode via UIScreen.MainScreen.CurrentMode.Size.
This issue does not appear to exist on the iPhone6S and iPhone6S+ and this issue can not be replicated on the simulator.
Here's how to activate zoom mode: https://support.apple.com/en-us/HT203073
I'm not sure if this is the most proper fix for this issue but I haven't been able to locate a better way to do this. Let me know if you have any feedback please. Thanks!

iPhone6 & iPhone6+ zoom mode detection

---

src/Forms/XLabs.Forms/Controls/RadioButton/BindableRadioGroup.cs

If your ItemSource contain an element with id = 0 it is not being checked on view load because OnSelectedItemChanged is not being fired. 
That's a problem with default bindableproperty value - it is 0 so app have no idea if the property has been changed.

fix RadioButton/BindableRadioGroup.cs

---

src/Forms/XLabs.Forms.WinRT.Shared/Controls/RadioButton/RadioButtonRenderer.cs
src/Forms/XLabs.Forms.WinRT.Shared/XLabs.Forms.WinRT.Shared.projitems

This commit adds the radio button control for Windows. It appears that this control was previously included for WindowsPhone, but was later dropped. This a port of that code from WindowsPhone to Windows.
You can find the original file [here](https://github.com/XLabs/Xamarin-Forms-Labs/commits/4d7d5568bc791d8693bf2ac87d19c6cd8429a210/src/Forms/XLabs.Forms.WP8/Controls/RadioButton/RadioButtonRenderer.cs).
I've tested and have this working in one of my projects.

Add Radio Button for Windows

---

build.ps1

$Env:Path can on many systems contain empty entries and on those Test-Path will fail and abort the script.

Fix env path can have empty entries in build.ps1

---

src/Forms/XLabs.Forms.Droid/Controls/HybridWebView/HybridWebViewRenderer.cs
src/Forms/XLabs.Forms/Controls/HybridWebView.cs

The following two **optional** properties were added to:
1) Enabling hardware acceleration on android devices via bindable property
2) Disabling additional gesture detector - removes lags on most new(6.0+) and old(4.4+) android devices during scrolling.
These changes improve performance of Hybridwebview on android devices. Most notably the scrolling lags.

Performance fixes:
